### ISSUE TITLE
   sxiv: no more files to display, aborting

### ISSUE THREAD

**Issue by 0rb677** [sdushantha/fontpreview#14]
on my system it displays the first font fine, 
then after selecting the second it doesnt display anything.
any chance to fix? thank you @sdushantha

**Comment by sdushantha** [comment]
@0rb677 Could you be so kind and send a screen recording of that is happening?

**Comment by 0rb677** [comment]
@sdushantha yes
```
asciinema play fontconfig.json
```
[fontpreview.zip](https://github.com/sdushantha/fontpreview/files/4176986/fontpreview.zip)

**Comment by SmartFinn** [comment]
Got the same on Fedora 31:

```sh
$ > fzf --version
0.20.0
$ > sxiv -v
sxiv 25
$ > bash -x ./fontpreview
++ mktemp -d --tmpdir fontpreview_dir_XXXXXXXX
+ FONTPREVIEW_DIR=/tmp/fontpreview_dir_ez1CV4HM
++ mktemp --tmpdir=/tmp/fontpreview_dir_ez1CV4HM fontpreview_XXXXXXXX.pid
+ PIDFILE=/tmp/fontpreview_dir_ez1CV4HM/fontpreview_CF71akJz.pid
++ mktemp --tmpdir=/tmp/fontpreview_dir_ez1CV4HM fontpreview_XXXXXXXX.png
+ FONT_PREVIEW=/tmp/fontpreview_dir_ez1CV4HM/fontpreview_KAfQT7vV.png
++ mktemp --tmpdir=/tmp/fontpreview_dir_ez1CV4HM fontpreview_XXXXXXXX.termpid
+ TERMWIN_IDFILE=/tmp/fontpreview_dir_ez1CV4HM/fontpreview_qYpLIhfy.termpid
+ VERSION=1.0.0
+ SEARCH_PROMPT='❯ '
+ SIZE=532x365
+ POSITION=+0+0
+ FONT_SIZE=38
+ BG_COLOR='#ffffff'
+ FG_COLOR='#000000'
+ PREVIEW_TEXT='ABCDEFGHIJKLM\nNOPQRSTUVWXYZ\nabcdefghijklm\nnopqrstuvwxyz\n1234567890\n!@$\%(){}[]'
+ trap '' SIGTSTP
+ trap pre_exit EXIT
++ getopt -o h --long position:,size:,version,search-prompt:,font-size:,bg-color:,fg-color:,preview-text:,help --
+ options=' --'
+ eval set -- ' --'
++ set -- --
+ true
+ case "$1" in
+ shift
+ break
+ main
+ dependencies=(xdotool sxiv convert fzf)
+ for dependency in "${dependencies[@]}"
+ type -p xdotool
+ for dependency in "${dependencies[@]}"
+ type -p sxiv
+ for dependency in "${dependencies[@]}"
+ type -p convert
+ for dependency in "${dependencies[@]}"
+ type -p fzf
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ xdotool getactivewindow
+ FIRST_RUN=true
+ true
++ convert -list font
++ awk -F: '/^[ ]*Font: /{print substr($NF,2)}'
++ fzf '--prompt=❯ '
+ font=AvantGarde-Book
+ [[ -z AvantGarde-Book ]]
+ generate_preview AvantGarde-Book
+ convert -size 532x365 xc:#ffffff -gravity center -pointsize 38 -font AvantGarde-Book -fill '#000000' -annotate +0+0 'ABCDEFGHIJKLM\nNOPQRSTUVWXYZ\nabcdefghijklm\nnopqrstuvwxyz\n1234567890\n!@$\%(){}[]' -flatten /tmp/fontpreview_dir_ez1CV4HM/fontpreview_KAfQT7vV.png
+ '[' true == true ']'
+ FIRST_RUN=false
+ sxiv -N fontpreview -b -g 532x365+0+0 /tmp/fontpreview_dir_ez1CV4HM/fontpreview_KAfQT7vV.png
++ cat /tmp/fontpreview_dir_ez1CV4HM/fontpreview_qYpLIhfy.termpid
+ xdotool windowfocus 29360142
+ echo 1527903
+ true
++ convert -list font
++ awk -F: '/^[ ]*Font: /{print substr($NF,2)}'
++ fzf '--prompt=❯ '
+ font=AvantGarde-Demi
+ [[ -z AvantGarde-Demi ]]
+ generate_preview AvantGarde-Demi
+ convert -size 532x365 xc:#ffffff -gravity center -pointsize 38 -font AvantGarde-Demi -fill '#000000' -annotate +0+0 'ABCDEFGHIJKLM\nNOPQRSTUVWXYZ\nabcdefghijklm\nnopqrstuvwxyz\n1234567890\n!@$\%(){}[]' -flatten /tmp/fontpreview_dir_ez1CV4HM/fontpreview_KAfQT7vV.png
sxiv: no more files to display, aborting
+ '[' false == true ']'
+ true
++ convert -list font
++ fzf '--prompt=❯ '
++ awk -F: '/^[ ]*Font: /{print substr($NF,2)}'
+ font=
+ [[ -z '' ]]
+ return
+ pre_exit
++ cat /tmp/fontpreview_dir_ez1CV4HM/fontpreview_CF71akJz.pid
+ kill -9 1527903
```

It seems sxiv doesn't reload the `$FONT_PREVIEW` file when it is overwritten.

**Comment by sdushantha** [comment]
@0rb677 @SmartFinn Could you guys try updating to the latest version of `sxiv`?
I am currently running the latest version and dont have a problem:
```bash
$ sxiv -v
sxiv 26
```

**Comment by SmartFinn** [comment]
@sdushantha unfortunately, upgrade to sxiv 26 didn't solve the issue. Let's find a difference in system setup.

It's not SElinux (I disabled it). It's not an tmpfs issue because I tried to save tmp files to btrfs with `env TMPDIR="$PWD" bash fontpreview` but got the same message.

**Comment by sdushantha** [comment]
Well, I dont know what to say about my system...
Here you have this in case that interests you:
```
$ uname -a
Linux unicorn 5.4.17-1-MANJARO #1 SMP PREEMPT Tue Feb 4 11:40:50 UTC 2020 x86_64 GNU/Linux
```

Is there something specific you want to know?

**Comment by SmartFinn** [comment]
@sdushantha could you upload /usr/bin/sxiv file here? I'll try to run on my system.

**Comment by sdushantha** [comment]
@SmartFinn 
https://0x0.st/i-i5.so

**Comment by SmartFinn** [comment]
@sdushantha Thanks. But no luck.

**Comment by kraem** [comment]
Also had this bug on `sxiv` 2.6 but was fixed with version 1.0.2 bump :)

**Comment by sdushantha** [comment]
@kraem Thank for letting us know about that!
@SmartFinn Did version 1.0.2 fix the issue for you?

**Comment by SmartFinn** [comment]
There is no 1.0.2 version. I tested with sxiv 1.3.2 with the following results: sxiv doesn't crash, but the newly generated image doesn't load.

**Comment by sdushantha** [comment]
@SmartFinn Oh sorry, my bad. I meant the latest version of `fontpreview` :)

**Comment by SmartFinn** [comment]
@sdushantha kinda, sxiv shows the generated image but:

![image](https://user-images.githubusercontent.com/819186/74135191-88f3bd80-4bf4-11ea-98a3-f1370948e5ea.png)

**Comment by sdushantha** [comment]
@SmartFinn 
#23 Would solve this problem, but I think it would take some time to make it

**Comment by 0rb677** [comment]
@sdushantha Hi. i just upgraded dom0 to fedora 31 (i use Qubes 4.1)
fzf - 0.20.0
sxiv - 25
xdotool - 3.20190727.1
ImageMagick - 6.9.10-86

No issues. Fontpreview works great.

**Comment by sdushantha** [comment]
> sxiv: no more files to display, aborting
Could you check if the image file still exists after getting that error message?

**Comment by sdushantha** [comment]
@0rb677 Could you try the latest version of `sxiv`?
https://github.com/muennich/sxiv/releases/tag/v26

**Comment by 0rb677** [comment]
@sdushantha got it.
```
[0rb@dom0 ~]$ sxiv -version
sxiv v26
[0rb@dom0 ~]$ fontpreview
sxiv: no more files to display, aborting
Restart sxiv - You maybe using a obsolete version. 
[0rb@dom0 ~]$ 
```

**Comment by sdushantha** [comment]
@0rb677 
> i also have ueberzug

That does not matter right now because `fontpreview` does not use it now.

Could you check if the image file still exists after you quit `fontpreview`?

**Comment by sdushantha** [comment]
It's been around 2 months and there is not activity. I will be closing this issue since I assume it might be fixed and for the sake of cleaning the open issues. I'll be more than happy to reopen this incase anyone encounters this issue again :)
