### ISSUE TITLE
[Feature Request] Add MacOS support

### ISSUE THREAD

**Issue by sdushantha** [sdushantha/fontpreview#15]
So far I have tried 3 image viewers:
- `macfeh` - Does not reload the image when the image gets altered. The normal `feh` has an `--auto-reload` option, but `macfeh` doesnt, and it does not look it will be added if we ask for it because the developer has not been active for a really long time.

- `qlmanage` (Quick Look) - Does not reload the image when the image gets altered

- Preview.app - Is able to reload the image using a small [hack](https://superuser.com/a/850828/1040587). But the down side of using preview is that it does not look minimal. It is possible to hide the tool bar and some of the junk, but I am not sure if it is possible to do so from the command line.

To change the focus from the image viewer back to the terminal, we can of course use Apple Script.

**Comment by sdushantha** [comment]
Small update:
![Screenshot 2020-02-15 at 13 41 36](https://user-images.githubusercontent.com/27065646/74588026-6ea54f80-4ff9-11ea-9a48-4e60d2dd4ae5.png)

I found out that `imagemagick` is not able to find fonts without Ghostscript on macOS.
After installing Ghostscript (`brew install gs`), doing `convert -list font` gave me the fonts.

Something else that I found out is that `mktemp` works differently on macOS. As you see in the screenshot (title of Preview.app), `mktemp` is not replacing the XXXXXX with the random letters for files.

**Comment by sdushantha** [comment]
Dropping this idea, because it takes too much time beceause I have to turn off and turn my laptop again to switch OS, to test the code on macOS and then test it on Linux to make sure it works fine. I am going to keep the _macos-beta_ branch in case someone wants to work on it or if I ever go back to working on it :)

**Comment by sdushantha** [comment]
I will not be creating a macOS version because for some strange reason, `imagemagick` is not able to find all the installed fonts on macOS. So I dont see the point of making a macOS version if the user cant see all their fonts.

CC @XOKP

**Comment by XOKP** [comment]
Thanks for your information, your effort on it is appreciated.
