### ISSUE TITLE
Have to click back to the terminal every time I load a font

### ISSUE THREAD

**Issue by hibatica** [sdushantha/fontpreview#25]
Every time I load a font, the window focus goes to the preview window and I have to click on the terminal to set focus back to the font selection.
Is it possible to make it retain focus on the font selection window (terminal)?

I'm sure not everything here is needed to reproduce but here is my current setup:

OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-6-amd64 
DE: KDE 
WM: KWin
WM Theme: Materia-Manjaro-Dark-Gradient
Theme: Breeze Dark [KDE], Breeze [GTK2/3]
Icons: Materia-Manjaro-Dark-2 [KDE], breeze [GTK2/3]
Terminal: konsole

**Comment by sdushantha** [comment]
Hmm...that is strange. Could this be something to do with KDE or KWin? Because this does not happen in i3wm.

**Comment by hibatica** [comment]
@sdushantha most likely. I don't know if support for multiple environments is your priority, but if it is then that would be a good fix. 
If I can figure out how the program works, maybe I can contribute myself

**Comment by hibatica** [comment]
I was searching for where I could add my code and I see there is already a section to maintain focus on the terminal window... maybe I need to use a different method for kde

**Comment by sdushantha** [comment]
@hibatica Yeah that could be it. I havent used KDE before, so I dont know much about it

**Comment by 0mp** [comment]
I have a similar issue with dwm on FreeBSD.

It looks like on each refresh sxiv is stealing the focus.

This could be a dwm thing, however.

@hibatica, let me know if you've got some patches to test.

**Comment by sdushantha** [comment]
@0mp Do you still have this issue?

**Comment by 0mp** [comment]
No, it works very nicely now. Thanks!

**Comment by sdushantha** [comment]
@hibatica I forgot to ask, do you still face this issue?
