### ISSUE TITLE
I want to display English and Korean together. Which file should I modify?

### ISSUE THREAD

**Issue by opqriu** [sdushantha/fontpreview#34]

**Comment by sdushantha** [comment]
Hi @opqriu 😊 

I dont think I fully understand what you are asking help for.

Do you want the preview image to show both Korean and English? If that's what you are asking for, then you can do this:

Add this to your `.bashrc` or `zshrc`
```
export FONTPREVIEW_PREVIEW_TEXT="Hello\n여보세요"
```

If the above does not answer your question, please do let me know and I will try to help you out

**Comment by opqriu** [comment]
It was solved.
Thank you!!  :)
