### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by 0mp** [sdushantha/fontpreview#35]
Hi!

I would be super nice if you could tag releases with `git tag`. It makes it much easier to track development and package this nice tool for various package managers.

Thanks!

**Comment by sdushantha** [comment]
@0mp Thats sounds like a nice idea, I will do it later today after reading about `git tag` (never used it before)

**Comment by 0mp** [comment]
That should be fairly simple, at minimum it could even be:

```
git tag 1.0.6
git push --tags
```

**Comment by sdushantha** [comment]
Done! 😊

**Comment by 0mp** [comment]
Thanks!
