### ISSUE TITLE
Info: Reimplementation in Emacs Lisp

### ISSUE THREAD

**Issue by SebastianMeisel** [sdushantha/fontpreview#37]
Hello,

I just want to inform you, that I started a reimplementation of fontpreview in Emacs Lisp,
because I often need fontnames for projects within Emacs. It's still in an early stage. Just
thought, you might want to know.
I gave you credits of course.

Sebastian Meisel

**Comment by sdushantha** [comment]
@SebastianMeisel Awesome! Let me know when you are finished so that I can take a look at it :grinning:

**Comment by SebastianMeisel** [comment]
Oh, I forgot the link. It's already a working kind of prototype: 
https://github.com/SebastianMeisel/fontpreview-mode.

**Comment by sdushantha** [comment]
@SebastianMeisel If I were you, I would put a nice demo gift or image in the start of the README so that when more people get attracted to your project ;)

**Comment by SebastianMeisel** [comment]
I did that and also added a few features. I think it usable by now.

**Comment by sdushantha** [comment]
Looks neat! Post it on Reddit and get some users :)

**Comment by SebastianMeisel** [comment]
Already done - well the posting part ;-)

Am Do., 30. Apr. 2020 um 21:29 Uhr schrieb Siddharth Dushantha <
notifications@github.com>:
