### ISSUE TITLE
Probably not intended install location for AUR package

### ISSUE THREAD

**Issue by CosmosAtlas** [sdushantha/fontpreview#8]
In the PKGBUILD file on AUR
```bash
package() {
  cd "$pkgname/"
  make DEST="$pkgdir/" install
  install -D -m644 LICENSE "$pkgdir/usr/share/licenses/fontpreview/LICENSE.md"
}
```

The executable will be located at root `/` by default which is probably not intended.

**Comment by sdushantha** [comment]
@elsorino Could please take a look at this?

**Comment by elsorino** [comment]
I've fixed it now

**Comment by sdushantha** [comment]
@CosmosAtlas This has been fixed now please try installing it again.

I'm going to close this issue as it has been fixed now 👍
